"""Make torch's `triton_helpers` importable from the torch-free tnpu venv.

Inductor's kernels call `triton_helpers.maximum`, `.max2`, `.sort_with_index`
and friends. The module is inside torch, and tnpu's venv deliberately has none,
so a kernel that uses one cannot compile there.

`triton_helpers.py` itself imports nothing from torch, only `.triton_compat`,
so it is copied verbatim next to the kernel and paired with the small
`triton_compat` below. Copying the installed torch's file rather than a vendored
snapshot keeps the helpers matched to the torch that generated the kernel.
"""

import os
import shutil

PACKAGE = "tnpu_helpers"

#: Stands in for torch._inductor.runtime.triton_compat, whose only job here is
#: to resolve these seven names. Mirrors the upstream fallbacks so a triton
#: version change lands the same way on both sides.
_COMPAT = '''\
"""Generated by PyTorchSimFrontend/triton_backend/helpers_shim.py. Do not edit."""

import inspect
from typing import Any

import triton
import triton.language as tl
from triton.runtime.jit import JITFunction  # noqa: F401

try:
    from triton.language.extra import libdevice  # noqa: F401

    libdevice = tl.extra.libdevice  # noqa: F811
    math = tl.math
except ImportError:
    if hasattr(tl.extra, "cuda") and hasattr(tl.extra.cuda, "libdevice"):
        libdevice = tl.extra.cuda.libdevice
        math = tl.math
    elif hasattr(tl.extra, "intel") and hasattr(tl.extra.intel, "libdevice"):
        libdevice = tl.extra.intel.libdevice
        math = tl.math
    else:
        libdevice = tl.math
        math = tl

try:
    from triton.language.standard import _log2
except ImportError:

    def _log2(x: Any) -> Any:
        raise NotImplementedError

builtins_use_semantic_kwarg = (
    "_semantic" in inspect.signature(triton.language.core.view).parameters
)
'''


def _source_path():
    from torch._inductor.runtime import triton_helpers
    return triton_helpers.__file__


def write_package(dest_dir):
    """Write the importable package next to a kernel. Returns the import line."""
    pkg = os.path.join(dest_dir, PACKAGE)
    os.makedirs(pkg, exist_ok=True)
    with open(os.path.join(pkg, "__init__.py"), "w"):
        pass
    with open(os.path.join(pkg, "triton_compat.py"), "w") as f:
        f.write(_COMPAT)
    shutil.copyfile(_source_path(), os.path.join(pkg, "triton_helpers.py"))
    return f"from {PACKAGE} import triton_helpers\n"
