"""ffn_erf -- the encoder ffn that represents serving: bias GEMMs, erf GELU.

GENERATED by gen_v6e_cases.py -- do not hand-edit.
Every case is a shape silicon ran; ref_v6e.csv carries its device time.
"""

PARAMS = "S, hidden, interm"

#: (name, size, origin, census, source, note).
#: origin  v6e (a real TPU v6e measured this exact shape)
#: census  exact (the measurement ran it; nothing here is interpolated)
CASES = [
    ("ffn_erf_1x384x1536", (1, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_1x768x3072", (1, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.4%"),
    ("ffn_erf_1x1024x4096", (1, 1024, 4096), "v6e", "exact", "bge-reranker-large", ""),
    ("ffn_erf_32x384x1536", (32, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_32x768x3072", (32, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.0%"),
    ("ffn_erf_32x1024x4096", (32, 1024, 4096), "v6e", "exact", "bge-reranker-large", ""),
    ("ffn_erf_128x384x1536", (128, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_128x768x3072", (128, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.1%"),
    ("ffn_erf_128x1024x4096", (128, 1024, 4096), "v6e", "exact", "bge-reranker-large", ""),
    ("ffn_erf_256x384x1536", (256, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_256x768x3072", (256, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.0%"),
    ("ffn_erf_512x384x1536", (512, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_512x768x3072", (512, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.1%"),
    ("ffn_erf_512x1024x4096", (512, 1024, 4096), "v6e", "exact", "bge-reranker-large", ""),
    ("ffn_erf_1024x384x1536", (1024, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_1024x768x3072", (1024, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.2%"),
    ("ffn_erf_1024x1024x4096", (1024, 1024, 4096), "v6e", "exact", "bge-reranker-large", ""),
    ("ffn_erf_2048x384x1536", (2048, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_2048x768x3072", (2048, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.1%"),
    ("ffn_erf_2048x1024x4096", (2048, 1024, 4096), "v6e", "exact", "bge-reranker-large", ""),
    ("ffn_erf_4096x384x1536", (4096, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_4096x768x3072", (4096, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.0%"),
    ("ffn_erf_4096x1024x4096", (4096, 1024, 4096), "v6e", "exact", "bge-reranker-large", ""),
    ("ffn_erf_8192x384x1536", (8192, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_8192x768x3072", (8192, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.0%"),
    ("ffn_erf_8192x1024x4096", (8192, 1024, 4096), "v6e", "exact", "bge-reranker-large", ""),
    ("ffn_erf_16384x384x1536", (16384, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_16384x768x3072", (16384, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.0%"),
    ("ffn_erf_32768x384x1536", (32768, 384, 1536), "v6e", "exact", "minilm-l6", ""),
    ("ffn_erf_32768x768x3072", (32768, 768, 3072), "v6e", "exact", "bge-reranker-base,e5-base", "같은 shape 을 잰 단위 2개, 편차 0.0%"),
    ("ffn_erf_32768x1024x4096", (32768, 1024, 4096), "v6e", "exact", "bge-reranker-large", ""),
]
