// GENERATED by pytorchsim-triton-compiler -- TOGSim trace producer (ABI v15). DO NOT EDIT.
// Each togsim_* call below lowers 1:1 to one of these free functions. Arg formats:
//   togsim_dma(ctx, dir, arg_id, offset, ndim, dims[], strides[], elem_bits,
//              is_async, sem, read_bufs[], n_read, write_bufs[], n_write, indirect)
//              dir: 0=load (MOVIN), 1=store (MOVOUT); indirect: 0 or 1
//   togsim_compute(ctx, tile_id, compute_type, ndim, dims[], read_bufs[], n_read,
//                  write_bufs[], n_write)   compute_type: 0=vector, 1=matmul, 2=preload,
//                                          3=cross-lane
//   togsim_memory_barrier(ctx, sem, expected)   // expected = elements signaled on sem
//   togsim_dispatch(ctx, tile_fn, iv[], n_iv, key)   // run one work-item
//   togsim_kernel(ctx, shape_args[], n_shape_args)   // producer entry point
#include <cstddef>
#include <cstdint>
using std::size_t;
#include "togsim_runtime.h"
extern const int32_t togsim_spad_buffer_count = 4;
extern const int64_t togsim_spad_buffer_bytes[4] = {1048576, 262144, 262144, 0};
static void togsim_kernel_tile(EmitCtx* v1, int64_t* v2, int32_t v3) {
  int32_t v4 = 512;
  int32_t v5 = 128;
  int32_t v6 = 0;
  size_t v7 = 512;
  size_t v8 = 0;
  size_t v9 = 1;
  size_t v10 = 2;
  int64_t v11 = 1;
  int64_t v12 = 0;
  int64_t v13 = v2[v12];
  ptrdiff_t v14 = (ptrdiff_t) v13;
  size_t v15 = (size_t) v14;
  int64_t v16 = v2[v11];
  ptrdiff_t v17 = (ptrdiff_t) v16;
  size_t v18 = (size_t) v17;
  ptrdiff_t v19 = (ptrdiff_t) v15;
  int32_t v20 = (int32_t) v19;
  ptrdiff_t v21 = (ptrdiff_t) v18;
  int32_t v22 = (int32_t) v21;
  togsim_compute(v1, 0, 0, 0, nullptr, nullptr, 0, (const int64_t[]){0}, 1);
  uint32_t v23 = (uint32_t) v20;
  uint32_t v24 = (uint32_t) v4;
  uint32_t v25 = v23 * v24;
  int32_t v26 = (int32_t) v25;
  ptrdiff_t v27 = (ptrdiff_t) v26;
  size_t v28 = (size_t) v27;
  uint32_t v29 = (uint32_t) v22;
  uint32_t v30 = (uint32_t) v4;
  uint32_t v31 = v29 * v30;
  int32_t v32 = (int32_t) v31;
  ptrdiff_t v33 = (ptrdiff_t) v32;
  size_t v34 = (size_t) v33;
  size_t v35 = v28 * v7;
  for (int32_t i36 = v6; i36 < v4; i36 += v5) {
    togsim_compute(v1, 1, 0, 0, nullptr, nullptr, 0, nullptr, 0);
    ptrdiff_t v37 = (ptrdiff_t) i36;
    size_t v38 = (size_t) v37;
    size_t v39 = v35 + v38;
    togsim_dma(v1, 0, 0, v39, 2, (const int64_t[]){128, 512}, (const int64_t[]){1, 512}, 32, 1, v8, nullptr, 0, (const int64_t[]){2}, 1, 0);
    togsim_compute(v1, 2, 0, 0, nullptr, nullptr, 0, nullptr, 0);
    size_t v40 = v38 * v7;
    size_t v41 = v40 + v34;
    togsim_dma(v1, 0, 1, v41, 2, (const int64_t[]){512, 128}, (const int64_t[]){1, 512}, 32, 1, v9, nullptr, 0, (const int64_t[]){1}, 1, 0);
    togsim_memory_barrier(v1, v8, 65536);
    togsim_memory_barrier(v1, v9, 65536);
    togsim_compute(v1, 3, 0, 0, nullptr, nullptr, 0, nullptr, 0);
    togsim_compute(v1, 4, 2, 0, nullptr, (const int64_t[]){1, 2}, 2, (const int64_t[]){3}, 1);
    togsim_compute(v1, 5, 1, 0, nullptr, (const int64_t[]){0, 1, 2, 3}, 4, (const int64_t[]){0}, 1);
  }
  size_t v42 = v35 + v34;
  togsim_dma(v1, 1, 2, v42, 2, (const int64_t[]){512, 512}, (const int64_t[]){1, 512}, 32, 1, v10, (const int64_t[]){0}, 1, nullptr, 0, 0);
  return;
}
extern "C" void togsim_kernel(EmitCtx* v1, int64_t* v2, int32_t v3) {
  int64_t v4 = 21;
  int64_t v5 = 1;
  size_t v6 = 0;
  size_t v7 = 1;
  int64_t v8 = 0;
  int64_t v9 = v2[v8];
  ptrdiff_t v10 = (ptrdiff_t) v9;
  size_t v11 = (size_t) v10;
  int64_t v12 = v2[v5];
  ptrdiff_t v13 = (ptrdiff_t) v12;
  size_t v14 = (size_t) v13;
  for (size_t i15 = v6; i15 < v11; i15 += v7) {
    for (size_t j16 = v6; j16 < v14; j16 += v7) {
      int64_t v17[2];
      ptrdiff_t v18 = (ptrdiff_t) i15;
      int64_t v19 = (int64_t) v18;
      v17[v8] = v19;
      ptrdiff_t v20 = (ptrdiff_t) j16;
      int64_t v21 = (int64_t) v20;
      v17[v5] = v21;
      ptrdiff_t v22 = (ptrdiff_t) i15;
      int64_t v23 = (int64_t) v22;
      ptrdiff_t v24 = (ptrdiff_t) j16;
      int64_t v25 = (int64_t) v24;
      uint64_t v26 = (uint64_t) v25;
      uint64_t v27 = (uint64_t) v4;
      uint64_t v28 = 64;
      bool v29 = v27 < v28;
      uint64_t v30 = 0;
      uint64_t v31 = v29 ? v26 << v27 : v30;
      int64_t v32 = (int64_t) v31;
      uint64_t v33 = (uint64_t) v23;
      uint64_t v34 = (uint64_t) v32;
      uint64_t v35 = v33 | v34;
      int64_t v36 = (int64_t) v35;
      togsim_dispatch(v1, togsim_kernel_tile, v17, 2, v36);
    }
  }
  return;
}

